name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Setup java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CartControllerTests
        id: cart-controller-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: CartControllerTests
          setup-command: ''
          command: mvn test -Dtest=CartControllerTests
          timeout: 10
          max-score: 25

      - name: OrderControllerTests
        id: order-controller-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: OrderControllerTests
          setup-command: ''
          command: mvn test -Dtest=OrderControllerTests
          timeout: 10
          max-score: 25

      - name: UserControllerTests
        id: user-controller-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: UserControllerTests
          setup-command: ''
          command: mvn test -Dtest=UserControllerTests
          timeout: 10
          max-score: 25

      - name: WishlistControllerTests
        id: wishlist-controller-tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: WishlistControllerTests
          setup-command: ''
          command: mvn test -Dtest=WishlistControllerTests
          timeout: 10
          max-score: 25

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          CART_CONTROLLER_TESTS_RESULTS: "${{steps.cart-controller-tests.outputs.result}}"
          ORDER_CONTROLLER_TESTS_RESULTS: "${{steps.order-controller-tests.outputs.result}}"
          USER_CONTROLLER_TESTS_RESULTS: "${{steps.user-controller-tests.outputs.result}}"
          WISHLIST_CONTROLLER_TESTS_RESULTS: "${{steps.wishlist-controller-tests.outputs.result}}"
        with:
          runners: cart-controller-tests,order-controller-tests,user-controller-tests,wishlist-controller-tests

